### ISSUE TITLE
请问cms的boot版本为什么改成了2.0

### ISSUE THREAD

**Issue by szp2016** [lh-1/clouddo#1]

**Comment by lh-1** [comment]
你好，因为我也刚接触springboot不久，所以没法给你很深奥的回复。以我的理解，把一个大项目拆分成多个微服务，各个微服务之间其实是相对独立的，一个服务中使用的具体框架版本并不会影响其他服务中的框架版本。多个微服务是多个小的项目，微服务提供的是服务，并不关心具体实现。



mjylh@aliyun.com
 
发件人： SunZhangpin
发送时间： 2018-08-16 08:07
收件人： lh-1/clouddo
抄送： Subscribed
主题： Re: [lh-1/clouddo] 请问cms的boot版本为什么改成了2.0 (#1)
Closed #1.

**Comment by szp2016** [comment]
了解了，谢谢

**Comment by szp2016** [comment]
了解了，谢谢
